---
services:
  clickhouse:
    image: bitnami/clickhouse:25.7.4
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - ${PWD}/clickhouse/rollup.xml:/etc/clickhouse-server/conf.d/rollup.xml
      - ${PWD}/clickhouse/graphite.xml:/etc/clickhouse-server/conf.d/graphite.xml
      - ${PWD}/clickhouse/dbinit.sh:/docker-entrypoint-startdb.d/dbinit.sh
      - ${PWD}/clickhouse/schema.sql:/docker-entrypoint-startdb.d/schema.sql
    networks:
      - metrics

  haggar:
    image: haggar
    command: -agents 1 -carbon carbon-clickhouse:2103 -metrics 100
    networks:
      - metrics

  carbon-clickhouse:
    image: lomik/carbon-clickhouse:latest
    volumes:
      - ${PWD}/carbon-clickhouse/carbon-clickhouse.toml:/carbon-clickhouse.toml
      - ${PWD}/clickhouse/rollup.xml:/rollup.xml
    ports:
      - '2103:2103'
    depends_on:
      - "clickhouse"
    command: carbon-clickhouse -config="/carbon-clickhouse.toml"
    networks:
      - metrics
  graphite-clickhouse:
    image: lomik/graphite-clickhouse:v0.13.0
    volumes:
      - ${PWD}/graphite-clickhouse/graphite-clickhouse.toml:/graphite-clickhouse.toml
      - ${PWD}/clickhouse/rollup.xml:/rollup.xml
    ports:
      - '9190:9190'
    depends_on:
      - "clickhouse"
    command: graphite-clickhouse -config="/graphite-clickhouse.toml"
    networks:
      - metrics
  carbonapi:
    image: ghcr.io/go-graphite/carbonapi:0.17
    volumes:
      - ${PWD}/carbonapi/carbonapi.yml:/etc/carbonapi.yml
    ports:
      - '8180:8180'
    depends_on:
      - "graphite-clickhouse"
    networks:
      - metrics

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    depends_on:
      - "carbonapi"
    networks:
      - metrics

volumes:
  clickhouse_data:
    driver: local

networks:
  metrics:
    driver: bridge
