version: '2'

services:
  clickhouse:
    image: docker.io/bitnami/clickhouse:22
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/bitnami/clickhouse
      - ${PWD}/clickhouse/rollup.xml:/etc/clickhouse-server/conf.d/rollup.xml
      - ${PWD}/clickhouse/graphite.xml:/etc/clickhouse-server/conf.d/graphite.xml
      - ${PWD}/clickhouse/dbinit.sh:/docker-entrypoint-startdb.d/dbinit.sh
      - ${PWD}/clickhouse/schema.sql:/docker-entrypoint-startdb.d/schema.sql

  haggar:
    image: egaillardon/haggar:latest
    command: -agents 1 -carbon carbon-clickhouse:2203 -metrics 100

  carbon-clickhouse:
    image: ghcr.io/go-graphite/carbon-clickhouse:latest
    volumes:
      - ${PWD}/carbon-clickhouse/carbon-clickhouse.toml:/carbon-clickhouse.toml
      - ${PWD}/clickhouse/rollup.xml:/rollup.xml
    ports:
      - '2203:2203'
    depends_on:
      - "clickhouse"
    command: carbon-clickhouse -config="/carbon-clickhouse.toml"

  graphite-clickhouse:
    image: ghcr.io/go-graphite/graphite-clickhouse:latest
    volumes:
      - ${PWD}/graphite-clickhouse/graphite-clickhouse.toml:/graphite-clickhouse.toml
      - ${PWD}/clickhouse/rollup.xml:/rollup.xml
    ports:
      - '9290:9290'
    depends_on:
      - "clickhouse"
    command: graphite-clickhouse -config="/graphite-clickhouse.toml"

  carbonapi:
    image: ghcr.io/go-graphite/carbonapi:latest
    volumes:
      - ${PWD}/carbonapi/carbonapi.yml:/etc/carbonapi.yml
    ports:
      - '8280:8280'
    depends_on:
      - "graphite-clickhouse"

  grafana:
    image: grafana/grafana:latest
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    volumes:
      - ${PWD}/grafana/provisioning:/etc/grafana/provisioning
    ports:
      - '3000:3000'
    depends_on:
      - "carbonapi"

volumes:
  clickhouse_data:
    driver: local
